### ISSUE TITLE
通讯录人名关系识别

### ISSUE THREAD

**Issue by qiaohaoforever** [yanwii/ChineseNER#1]
很高兴发现这么棒的项目，学习了几天～
有一个问题想请教一下：
面对像通讯录那种“大舅、杨三姐、王欢处长”这种类型的文本可以利用你这种方案解决吗？
想了挺久的，文本长度太短了，原子化的文本查找有效姓名、关系等信息
期盼探讨～

**Comment by qiaohaoforever** [comment]
已加微信，等你回复

**Comment by liutianling** [comment]
@qiaohaoforever 这个项目确实很棒，按照作者说的可以跑吗？model.py里面根本没有主函数入口啊,main.py里面也没有参数　-m啊，你是怎么跑成功的呢？求教。

**Comment by renmengxing12** [comment]
![image](https://user-images.githubusercontent.com/46949893/62093303-5b27d680-b2ab-11e9-917d-6107020a6df9.png)

 self.checkpoint_dir = "./model/"  
  self.checkpoint_path = "./model/ner.org.ckpt" 
 在model.py中请问这个文件在哪里？是自己创建文件夹 然后生成模型输出到文件夹中吗？

另外我运行之后报错 ：

ERROR:tensorflow:Couldn't match files for checkpoint bert_model/model.ckpt-0
Traceback (most recent call last):
  File "model.py", line 507, in <module>
    model.train()
  File "model.py", line 333, in train
    modeling.get_assignment_map_from_checkpoint(tvars,ARGS.init_checkpoint)
  File "/home/tianye/RMX/ChineseNER-master/bert_base/bert/modeling.py", line 331, in get_assignment_map_from_checkpoint
    init_vars = tf.train.list_variables(init_checkpoint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 95, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 63, in load_checkpoint
    "given directory %s" % ckpt_dir_or_file)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory bert_model/


怎么解决啊？ 谢谢！

**Comment by yanwii** [comment]
plz reference #2  & #3

**Comment by SuiMingYang** [comment]
> @qiaohaoforever 这个项目确实很棒，按照作者说的可以跑吗？model.py里面根本没有主函数入口啊,main.py里面也没有参数　-m啊，你是怎么跑成功的呢？求教。

main函数里arg判断去掉，都用默认的跑就行了

**Comment by SuiMingYang** [comment]
> ![image](https://user-images.githubusercontent.com/46949893/62093303-5b27d680-b2ab-11e9-917d-6107020a6df9.png)
> 
> self.checkpoint_dir = "./model/"
> self.checkpoint_path = "./model/ner.org.ckpt"
> 在model.py中请问这个文件在哪里？是自己创建文件夹 然后生成模型输出到文件夹中吗？
> 
> 另外我运行之后报错 ：
> 
> ERROR:tensorflow:Couldn't match files for checkpoint bert_model/model.ckpt-0
> Traceback (most recent call last):
> File "model.py", line 507, in
> model.train()
> File "model.py", line 333, in train
> modeling.get_assignment_map_from_checkpoint(tvars,ARGS.init_checkpoint)
> File "/home/tianye/RMX/ChineseNER-master/bert_base/bert/modeling.py", line 331, in get_assignment_map_from_checkpoint
> init_vars = tf.train.list_variables(init_checkpoint)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 95, in list_variables
> reader = load_checkpoint(ckpt_dir_or_file)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 63, in load_checkpoint
> "given directory %s" % ckpt_dir_or_file)
> ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory bert_model/
> 
> 怎么解决啊？ 谢谢！

一样的问题，怎么解决的，这个地方一会要文件一会要目录的，搞不懂了
