### ISSUE TITLE
bert_data_utils.py文件中 错误ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by impltrait** [yanwii/ChineseNER#11]
Traceback (most recent call last):
  File "model.py", line 505, in <module>
    model.train()
  File "model.py", line 284, in train
    self.train_data = BertDataUtils(tokenizer, batch_size=5)
  File "C:\Users\admin\Desktop\ChineseNER\bert_data_utils.py", line 28, in __init__
    self.prepare_batch()
  File "C:\Users\admin\Desktop\ChineseNER\bert_data_utils.py", line 77, in prepare_batch
    pad_data = self.pad_data(self.data[-self.batch_size:])
  File "C:\Users\admin\Desktop\ChineseNER\bert_data_utils.py", line 87, in pad_data
    max_length = max([len(i[0]) for i in c_data] )
ValueError: max() arg is an empty sequence

这个问题怎么解决

**Comment by yanwii** [comment]
```self.data[-self.batch_size:]``` 是空列表
