### ISSUE TITLE
python 停止工作

### ISSUE THREAD

**Issue by CrawlingForward** [yanwii/ChineseNER#13]
首先感谢大佬开源了这么好的项目。
有一个小疑问，存放bert模型的文件夹是‘model’还是‘bert_model’，按照说明里是‘bert_model’，但我跑的时候会出现如下错误：
```
Traceback (most recent call last):
  File "model.py", line 502, in <module>
    model.train()
  File "model.py", line 328, in train
    ARGS.init_checkpoint)
  File "D:\ProgramData\Anaconda3\lib\site-packages\bert_base-0.0.9-py3.6.egg\bert_base\bert\modeling.py", line 331, in get_assignment_map_from_checkpoint
    init_vars = tf.train.list_variables(init_checkpoint)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\checkpoint_utils.py", line 97, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\checkpoint_utils.py", line 65, in load_checkpoint
    "given directory %s" % ckpt_dir_or_file)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory bert_model/
```
改成‘model’之后运行就出现python停止运行的问题。
小白一枚，还请大神指正！

**Comment by nicken** [comment]
见#2

**Comment by yanwii** [comment]
#2
