### ISSUE TITLE
学习率 这个地方报错了

### ISSUE THREAD

**Issue by zdx1012** [yanwii/ChineseNER#15]
`epoch 0
Traceback (most recent call last):
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 300, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 3567, in _as_graph_element_locked
    types_str))
TypeError: Can not convert a float into a Tensor or Operation.
`

`TypeError: Fetch argument 5e-05 has invalid type <class 'float'>, must be a string or Tensor. (Can not convert a float into a Tensor or Operation.)

`

这个地方该怎么设置，求解决办法，感谢

**Comment by zdx1012** [comment]
```
          epoch 0
Traceback (most recent call last):
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 300, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 3567, in _as_graph_element_locked
    types_str))
TypeError: Can not convert a float into a Tensor or Operation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model.py", line 623, in <module>
    model.train()
  File "model.py", line 352, in train
    sess, batch
  File "model.py", line 277, in bert_step
    [self.embedded, self.global_steps, self.loss, self.train_op, self.logits, self.accuracy, self.length], feed_dict=feed)
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 471, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 261, in for_fetch
    return _ListFetchMapper(fetch)
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 370, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 370, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 261, in for_fetch
    return _ListFetchMapper(fetch)
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 370, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 370, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 271, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "D:\ProgramFiles\anaconda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 304, in __init__
    (fetch, type(fetch), str(e)))
TypeError: Fetch argument 5e-05 has invalid type <class 'float'>, must be a string or Tensor. (Can not convert a float into a Tensor or Operation.)


```

**Comment by zdx1012** [comment]
```
        self.train_op = create_optimizer(
            self.loss, self.learning_rate, num_train_steps, num_warmup_steps, False
        )
```
model.py  226行
是这个地方的参数出的问题吗
