### ISSUE TITLE
Couldn't find 'checkpoint' file or checkpoints in given directory

### ISSUE THREAD

**Issue by SeekPoint** [yanwii/ChineseNER#2]
ub16c9@ub16c9-gpu:~/ub16_prj/ChineseNER$ python3 model.py -e train -m bert
--------------------------------------------------
train data:	 2757
nums of tags:	 9
/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2019-03-12 17:25:23.711894: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-12 17:25:23.825882: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-03-12 17:25:23.826463: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.11GiB
2019-03-12 17:25:23.826481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-03-12 17:25:24.069500: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-12 17:25:24.069536: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-03-12 17:25:24.069542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-03-12 17:25:24.069766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9769 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "model.py", line 502, in <module>
    model.train()
  File "model.py", line 328, in train
    ARGS.init_checkpoint)
  File "/usr/local/lib/python3.5/dist-packages/bert_base/bert/modeling.py", line 331, in get_assignment_map_from_checkpoint
    init_vars = tf.train.list_variables(init_checkpoint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 95, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 63, in load_checkpoint
    "given directory %s" % ckpt_dir_or_file)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory bert_model/
ub16c9@ub16c9-gpu:~/ub16_prj/ChineseNER$ ll bert_
bert_data_utils.py  bert_model/         
ub16c9@ub16c9-gpu:~/ub16_prj/ChineseNER$ ll bert_model/
total 804848
drwxrwxr-x 3 ub16c9 ub16c9      4096 三月 12 17:25 ./
drwxrwxr-x 7 ub16c9 ub16c9      4096 三月 12 17:19 ../
-rw-r--r-- 1 ub16c9 ub16c9       520 三月 12 17:19 bert_config.json
-rw-r--r-- 1 ub16c9 ub16c9 411529768 三月 12 17:19 bert_model.ckpt.data-00000-of-00001
-rw-r--r-- 1 ub16c9 ub16c9      8512 三月 12 17:19 bert_model.ckpt.index
-rw-r--r-- 1 ub16c9 ub16c9    905069 三月 12 17:19 bert_model.ckpt.meta
drwxr-xr-x 2 ub16c9 ub16c9      4096 三月 12 17:16 chinese_L-12_H-768_A-12/
-rw-rw-r-- 1 ub16c9 ub16c9 411575980 三月 12 17:19 pytorch_model.bin
-rw-r--r-- 1 ub16c9 ub16c9    109540 三月 12 17:19 vocab.txt
ub16c9@ub16c9-gpu:~/ub16_prj/ChineseNER$

**Comment by yanwii** [comment]
在 **bert_model** 下新建文件 **checkpoint**, 内容如下:

```
model_checkpoint_path: "bert_model.ckpt"
all_model_checkpoint_paths: "bert_model.ckpt"
```
P.S. 还需要在根目录下创建 **model** 文件夹

**Comment by SeekPoint** [comment]
it's cool
