### ISSUE TITLE
您好，我加载bert初始模型总会报错。

### ISSUE THREAD

**Issue by CourteousWood** [yanwii/ChineseNER#3]

**Comment by CourteousWood** [comment]
![image](https://user-images.githubusercontent.com/26274922/55371025-3dca4200-552f-11e9-886c-05480b74a785.png)
`Traceback (most recent call last):
  File "/nfs/private/ly_03_20/bertNer/ChineseNER-master/model.py", line 502, in <module>
    model.train()
  File "/nfs/private/ly_03_20/bertNer/ChineseNER-master/model.py", line 328, in train
    ARGS.init_checkpoint)
  File "/home/luban/anaconda3/envs/py3/lib/python3.6/site-packages/bert_base/bert/modeling.py", line 331, in get_assignment_map_from_checkpoint
    init_vars = tf.train.list_variables(init_checkpoint)
  File "/home/luban/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 94, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/home/luban/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 62, in load_checkpoint
    "given directory %s" % ckpt_dir_or_file)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory bert_model/`

**Comment by CourteousWood** [comment]
`Traceback (most recent call last):
  File "/nfs/private/ly_03_20/bertNer/ChineseNER-master/model.py", line 502, in <module>
    model.train()

  File "/nfs/private/ly_03_20/bertNer/ChineseNER-master/model.py", line 328, in train
    ARGS.init_checkpoint)

  File "/home/luban/anaconda3/envs/py3/lib/python3.6/site-packages/bert_base/bert/modeling.py", line 331, in get_assignment_map_from_checkpoint init_vars = tf.train.list_variables(init_checkpoint)
  File "/home/luban/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 94, in list_variables

    reader = load_checkpoint(ckpt_dir_or_file)
  File "/home/luban/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 62, in load_checkpoint
    "given directory %s" % ckpt_dir_or_file)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory bert_model/`

**Comment by yanwii** [comment]
两步，
把 **bert_model/chinese_L-12_H-768_A-12** 下的文件移到 **bert_model** 下  
然后在 **bert_model** 下新建一个 **checkpoint** 文件, 内容为:

```
model_checkpoint_path: "bert_model.ckpt"
all_model_checkpoint_paths: "bert_model.ckpt"
```
